name: 'Develop Merged'

on:
  pull_request:
    types: [closed]
    branches: [develop]
  push:
    branches: [develop]

jobs:
  gather-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "merged_branch=${{ github.head_ref }}" >> "$GITHUB_OUTPUT"

  push-stg:
    needs: gather-pr
    runs-on: ubuntu-latest
    steps:
      - run: echo '=== Staging ==='
      - run: echo '${{ github.event_name }}'
      - run: echo '${{ needs.gather-pr.outputs.merged_branch }}'
      - run: echo "${{ toJson(github) }}"

  push-prd:
    needs: gather-pr
    if: github.event_name == 'push' && startsWith(needs.gather-pr.outputs.merged_branch, 'prd/')
    runs-on: ubuntu-latest
    steps:
      - run: echo '=== Production ==='