name: 'Develop Merged'

on:
  pull_request:
    types: [closed]
    branches: [develop]

jobs:
  gather-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      merged_branch: ${{ steps.check.outputs.merged_branch }}
    steps:
      - id: check
        run: echo "merged_branch=${{ github.head_ref }}" >> "$GITHUB_OUTPUT"

  push-stg:
    needs: gather-pr
    if: startsWith(needs.gather-pr.outputs.merged_branch, 'stg/')
    runs-on: ubuntu-latest
    steps:
      - run: echo '=== Staging ==='

  push-prd:
    needs: gather-pr
    if: startsWith(needs.gather-pr.outputs.merged_branch, 'prd/')
    runs-on: ubuntu-latest
    steps:
      - run: echo '=== Production ==='